### PR TITLE
Run flake8 in warning only mode on Python 2 and 3

### PR DESCRIPTION
**Pull request by cclauss**
This will help us find and fix the Python 3 syntax errors (print_function, etc.)  A step towards the resolution of https://github.com/100/Solid/issues/6

### CODE REVIEW

**Comment by cclauss** [comment]
This is **ready for review**.  I have used flake8 to clear the obvious Python3 incompatibilities so now py.tests run on Python 3.  They fail and need to be fixed but that is beyond the scope of this PR.

**Comment by 100** [comment]
Thank you, I'll look into fixing the test issues.

**Comment by emre-e** [comment]
Hi! I fixed the issues that causes the test to fails for python3 here. Could you please review? Here is my PR:
https://github.com/cclauss/Solid/pull/1/files

**Comment by cclauss** [comment]
Awesome work @emre-e with the slick fixes.

**Comment by cclauss** [comment]
Ready for review.

**Comment by 100** [comment]
Thanks, I'll take a look in a few days and merge it in.

**Pull request merged**
